# Generated by Django 5.1.6 on 2025-03-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='hotel_image',
            field=models.ImageField(blank=True, default='hotel_images/default_image.jpg', null=True, upload_to='hotel_images/'),
        ),
    ]
