# Generated by Django 5.1.2 on 2025-03-09 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0002_hotel_hotel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='hotel_image',
            field=models.ImageField(blank=True, default='room_images/default_image.jpg', null=True, upload_to='room_images/'),
        ),
    ]
