# Generated by Django 5.1.2 on 2025-03-09 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0003_room_hotel_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='hotel_image',
            new_name='room_image',
        ),
    ]
