# Generated by Django 5.1.7 on 2025-03-20 18:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0005_alter_booking_check_in_alter_booking_check_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='check_in',
            field=models.DateField(default=datetime.datetime(2025, 3, 20, 18, 33, 25, 179436, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='room',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
